### ISSUE TITLE
Pagination breaks after 10000 values

### ISSUE THREAD

**Issue by Avasam** [speedruncom/api#147] opened 2022-02-19 15:23 UTC
`https://www.speedrun.com/api/v1/runs?max=200&offset=9801`

```json
{
  "status": 400,
  "message": "Invalid pagination values.",
  "links": [
    {
      "rel": "support",
      "uri": "irc://speedrunslive.com#speedrun.com"
    },
    {
      "rel": "report-issues",
      "uri": "https://github.com/speedruncom/api/issues"
    }
  ]
}
```

**Comment by AnInternetTroll** [comment] 2022-02-19 15:26
Duplicate of #109 and #125

**Closed as completed** 2022-02-19 16:14 UTC
